# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Setup bazelisk for bazel builds
      #   uses: holvonix-open/setup-bazelisk@v0.6.0
      - name: Install Bazelisk
        uses: tullyliu/bazelisk-action@1.2
        with:
          # [required]
          # Version of Bazelisk we would like to install, defaults to 1.5.0
          version: '1.5.0'
          # [required]
          # Install path for Bazelisk binaries, defaults to ./.local/bin
          bazel-install-path: './.local/bin'
          # [required]
          # The OS of the system that wishes to install Bazelisk. Can be 'darwin' or 'linux'
          os: 'linux'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Figure out where we are
        run: |
          pwd
          ls -la

      - name: Build all targets
        run: bazel build //...

      - name: Test all targets
        run: bazel test //...
